data:
  sequence: '01'
  main_path: '../datasets/sequences/{}/'
  pose_path: '../datasets/poses/{}.txt'

parameters:
  rgb: False
  rectified: True
  detector: 'sift'
  distance_threshold: 0.30
  max_depth: 3000
  subset: null
